import { Translation } from './types';

export const TRANSLATIONS: Record<'en' | 'pl', Translation> = {
  en: {
    title: 'Hacker Mode', library: 'Library', store: 'Store',
    settings: 'Settings', hacker_menu: 'Hacker Menu', back: 'Back',
    close: 'Close', search: 'Search games...',
    audio: 'Audio', increase_volume: 'Vol +', decrease_volume: 'Vol -', toggle_mute: 'Mute',
    display: 'Display', increase_brightness: 'Brighter', decrease_brightness: 'Darker', toggle_theme: 'Theme',
    network: 'Network', wifi_settings: 'Wi-Fi Networks', toggle_wifi: 'Wi-Fi', bluetooth: 'Bluetooth',
    connect: 'Connect', scan: 'Scan', no_networks: 'No networks found',
    no_selection: 'Select a network', password: 'Password', wifi_on: 'On', wifi_off: 'Off',
    power: 'Power Profile', power_saving: 'Power Saver', balanced: 'Balanced', performance: 'Performance',
    general: 'General', language: 'Language',
    gaming_tools: 'Gaming Tools', enable_gamescope: 'Gamescope', enable_mangohud: 'MangoHUD', enable_vkbasalt: 'vkBasalt',
    library_settings: 'Library', close_on_launch: 'Close on game launch', reopen_on_exit: 'Reopen on game exit',
    proton_manager: 'Proton Manager', install_proton: 'Install', system_update: 'System Update', proton: 'Proton',
    add_game: 'Add Game',
    system: { shutdown: 'Shutdown', restart: 'Restart', sleep: 'Sleep', hibernate: 'Hibernate', logout: 'Log Out', switch_desktop: 'Switch to Desktop', switch_user: 'Switch User' },
    play: 'Play', install: 'Install', uninstall: 'Uninstall',
    last_played: 'Last played', play_time: 'Play time', never_played: 'Never played',
    imported: 'Imported', all_games: 'All', installed_only: 'Installed', favorites: 'Favorites',
    importing: 'Importing...', import_complete: 'Done', no_games: 'No games. Import your library.',
    game_source: { steam: 'Steam', epic: 'Epic Games', gog: 'GOG', amazon: 'Amazon', lutris: 'Lutris', manual: 'Manual' },
  },
  pl: {
    title: 'Hacker Mode', library: 'Biblioteka', store: 'Sklep',
    settings: 'Ustawienia', hacker_menu: 'Menu Hackera', back: 'Wróć',
    close: 'Zamknij', search: 'Szukaj gier...',
    audio: 'Dźwięk', increase_volume: 'Głośniej', decrease_volume: 'Ciszej', toggle_mute: 'Wycisz',
    display: 'Ekran', increase_brightness: 'Jaśniej', decrease_brightness: 'Ciemniej', toggle_theme: 'Motyw',
    network: 'Sieć', wifi_settings: 'Sieci Wi-Fi', toggle_wifi: 'Wi-Fi', bluetooth: 'Bluetooth',
    connect: 'Połącz', scan: 'Skanuj', no_networks: 'Brak sieci',
    no_selection: 'Wybierz sieć', password: 'Hasło', wifi_on: 'Wł.', wifi_off: 'Wył.',
    power: 'Profil zasilania', power_saving: 'Oszczędzanie', balanced: 'Zrównoważony', performance: 'Wydajność',
    general: 'Ogólne', language: 'Język',
    gaming_tools: 'Gaming', enable_gamescope: 'Gamescope', enable_mangohud: 'MangoHUD', enable_vkbasalt: 'vkBasalt',
    library_settings: 'Biblioteka', close_on_launch: 'Zamknij przy starcie gry', reopen_on_exit: 'Otwórz po zamknięciu',
    proton_manager: 'Menedżer Proton', install_proton: 'Zainstaluj', system_update: 'Aktualizacja', proton: 'Proton',
    add_game: 'Dodaj grę',
    system: { shutdown: 'Wyłącz', restart: 'Restart', sleep: 'Uśpij', hibernate: 'Hibernuj', logout: 'Wyloguj', switch_desktop: 'Pulpit', switch_user: 'Zmień użytkownika' },
    play: 'Graj', install: 'Zainstaluj', uninstall: 'Odinstaluj',
    last_played: 'Ostatnio grano', play_time: 'Czas gry', never_played: 'Nigdy nie grano',
    imported: 'Zaimportowano', all_games: 'Wszystkie', installed_only: 'Zainstalowane', favorites: 'Ulubione',
    importing: 'Importowanie...', import_complete: 'Gotowe', no_games: 'Brak gier. Zaimportuj bibliotekę.',
    game_source: { steam: 'Steam', epic: 'Epic Games', gog: 'GOG', amazon: 'Amazon', lutris: 'Lutris', manual: 'Ręcznie' },
  },
};
